#!/usr/bin/env python3
"""
Score donor alignment: how often does each member vote in line
with their actual top PAC donors' interests?

Approach:
- Uses each member's ACTUAL top PAC donors (by amount)
- Maps PAC names to policy categories using a registry
- Matches votes to categories using keywords in vote descriptions
- Deduplicates by bill number (keeps the most substantive vote)
- Weights alignment score by donation amount
- Calls out specific donor names in examples

Outputs: data/raw/donor_alignment.json
"""

import json
import os
import re
import sys
import time
import urllib.request
import urllib.error

import csv

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "raw")
PUBLIC_MEMBERS_DIR = os.path.join(os.path.dirname(__file__), "..", "public", "data", "members")
CACHE_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "scripts", ".cache")
ENV_LOCAL = os.path.join(os.path.dirname(__file__), "..", ".env.local")


def load_dotenv(path=ENV_LOCAL):
    """Load key=value pairs from .env.local into os.environ (won't overwrite)."""
    if not os.path.exists(path):
        return
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())


# Directory containing pre-computed LLM classifications of bill positions
# per industry category. Generated by running a classification agent.
LLM_POSITIONS_DIR = os.path.join(CACHE_DIR, "llm_donor_positions")


def parse_voteview_bill(bill_str):
    """
    Parse a Voteview bill string like 'HR1234' into (bill_type, number).
    Returns (type_slug, number_str) for Congress.gov API, e.g. ('hr', '1234').
    Returns (None, None) if unparseable.
    """
    if not bill_str:
        return None, None
    bill_str = bill_str.strip()
    # Order matters: check longer prefixes first
    for prefix, slug in [
        ("HCONRES", "hconres"), ("SCONRES", "sconres"),
        ("HJRES", "hjres"), ("SJRES", "sjres"),
        ("HRES", "hres"), ("SRES", "sres"),
        ("HR", "hr"), ("S", "s"),
    ]:
        if bill_str.upper().startswith(prefix):
            num = bill_str[len(prefix):]
            if num.isdigit():
                return slug, num
            break
    return None, None


def fetch_bill_subjects(congresses=None):
    """
    Fetch policy_area for all bills in our Voteview rollcall data.
    Uses the Congress.gov API with caching.
    Returns dict: "HR1234" -> "Health" (bill_str -> policy_area name).
    """
    load_dotenv()
    api_key = os.environ.get("CONGRESS_API_KEY", "")
    if not api_key:
        print("  No CONGRESS_API_KEY set — skipping policy_area fetching.")
        return {}

    if congresses is None:
        congresses = [114, 115, 116, 117, 118, 119]

    os.makedirs(CACHE_DIR, exist_ok=True)
    all_subjects = {}

    for congress in congresses:
        cache_path = os.path.join(CACHE_DIR, f"bill_subjects_{congress}.json")

        # Load cache if exists
        if os.path.exists(cache_path):
            with open(cache_path) as f:
                cached = json.load(f)
            all_subjects.update(cached)
            print(f"  Congress {congress}: loaded {len(cached)} cached bill subjects")
            continue

        # Collect unique bill numbers from rollcall CSVs for this congress
        bills_to_fetch = set()
        for prefix in ["H", "S"]:
            rc_path = os.path.join(CACHE_DIR, f"{prefix}{congress}_rollcalls.csv")
            if not os.path.exists(rc_path):
                continue
            with open(rc_path) as f:
                for row in csv.DictReader(f):
                    bn = (row.get("bill_number") or "").strip()
                    if bn:
                        bills_to_fetch.add(bn)

        if not bills_to_fetch:
            print(f"  Congress {congress}: no rollcall data found")
            continue

        print(f"  Congress {congress}: fetching policy_area for {len(bills_to_fetch)} bills...")
        congress_subjects = {}
        fetched = 0
        errors = 0

        for bill_str in sorted(bills_to_fetch):
            bill_type, bill_num = parse_voteview_bill(bill_str)
            if not bill_type:
                continue

            url = (
                f"https://api.congress.gov/v3/bill/{congress}/{bill_type}/{bill_num}"
                f"?api_key={api_key}&format=json"
            )
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "CivicReceipts/1.0"})
                resp = urllib.request.urlopen(req, timeout=15)
                data = json.loads(resp.read().decode())
                pa = data.get("bill", {}).get("policyArea", {})
                if pa and pa.get("name"):
                    congress_subjects[bill_str] = pa["name"]
                fetched += 1
            except urllib.error.HTTPError as e:
                if e.code == 404:
                    pass  # Bill not found — skip
                elif e.code == 429:
                    print(f"    Rate limited — pausing 60s...")
                    time.sleep(60)
                    errors += 1
                else:
                    errors += 1
            except Exception:
                errors += 1

            # Rate limit: ~5 requests/second to stay well under 1000/hour
            if fetched % 5 == 0:
                time.sleep(1.1)

            if fetched % 100 == 0 and fetched > 0:
                print(f"    ...fetched {fetched}/{len(bills_to_fetch)}")

        # Save cache
        with open(cache_path, "w") as f:
            json.dump(congress_subjects, f, indent=2)

        all_subjects.update(congress_subjects)
        print(f"  Congress {congress}: got policy_area for {len(congress_subjects)}/{len(bills_to_fetch)} bills ({errors} errors)")

    return all_subjects

# ── PAC Registry ──────────────────────────────────────────────────────
# Maps PAC name patterns to policy categories. Industry position preferences
# on specific bills are determined by pre-computed LLM classifications
# stored in LLM_POSITIONS_DIR, not by keyword matching.
PAC_REGISTRY = {
    "LABOR": {
        "patterns": [
            "LETTER CARRIERS", "CARPENTERS", "TEACHERS COPE",
            "MACHINISTS", "AFSCME", "AFL-CIO", "LABORER",
            "COMMUNICATIONS WORKERS", "TRANSPORT WORKERS",
            "FIRE FIGHTERS", "PILOTS ASSOCIATION", "TEAMSTERS",
            "SEIU", "IBEW", "AUTO WORKERS", "PLUMBERS",
            "IRONWORKERS", "STEELWORKERS", "ENGINEERS POLITICAL",
            "AMERICAN FEDERATION OF STATE",
            "AIR TRAFFIC CONTROLLERS", "TREASURY EMPLOYEES UNION",
            "NEA FUND FOR CHILDREN", "NATIONAL EDUCATION ASSOCIATION",
            "RETIRED FEDERAL EMP", "NARFE",
            "DIRECTORS GUILD", "DGA-PAC",
            "HEALTH JOBS JUSTICE",
            "POSTAL WORKERS", "USPS",
        ],
        "label": "Labor unions",
    },
    "HEALTHCARE": {
        "patterns": [
            "DENTAL ASSOCIATION", "HOSPITAL ASSOCIATION",
            "AMERICAN MEDICAL", "AFLAC", "DAVITA", "KAISER",
            "PHARMACEUTICAL", "PFIZER", "MERCK", "ABBOTT",
        ],
        "label": "Healthcare industry",
    },
    "REAL_ESTATE": {
        "patterns": [
            "REALTORS", "MULTI HOUSING", "HOME DEPOT",
            "HOMEBUILDERS", "MORTGAGE BANKERS",
            "MULTIFAMILY HOUSING COUNCIL",
        ],
        "label": "Real estate industry",
    },
    "DEFENSE": {
        "patterns": [
            "L3HARRIS", "LOCKHEED", "RAYTHEON", "NORTHROP",
            "BAE SYSTEMS", "BOEING", "GENERAL DYNAMICS",
            "BOOZ ALLEN", "LEIDOS",
            "TRANSDIGM",
        ],
        "label": "Defense contractors",
    },
    "TELECOM": {
        "patterns": [
            "COMCAST", "AT&T", "VERIZON", "CHARTER",
            "T-MOBILE", "NBCUNIVERSAL",
        ],
        "label": "Telecom companies",
    },
    "TECH": {
        "patterns": [
            "GOOGLE", "MICROSOFT", "CISCO", "DROPBOX",
            "ORACLE", "APPLE", "META", "AMAZON",
            "HEWLETT PACKARD", "SIEMENS",
        ],
        "label": "Tech companies",
    },
    "FINANCE": {
        "patterns": [
            "GOLDMAN", "JPMORGAN", "CITIGROUP", "BANK OF AMERICA",
            "CREDIT UNION", "VISA", "MASTERCARD", "BLACKSTONE",
            "MORGAN STANLEY", "WELLS FARGO",
            "AMALGAMATED BANK", "FIDELITY BROKERAGE",
            "FIDELITY INVESTMENTS", "CAPITAL GROUP",
        ],
        "label": "Financial industry",
    },
    "ENERGY_FOSSIL": {
        "patterns": [
            "PETROLEUM", "CHEVRON", "EXXON", "KOCH",
            "PIPELINE", "NATURAL GAS", "COAL",
        ],
        "label": "Fossil fuel industry",
    },
    "ENERGY_CLEAN": {
        "patterns": [
            "SOLAR", "WIND ENERGY", "CLEAN ENERGY",
            "LEAGUE OF CONSERVATION", "SIERRA",
        ],
        "label": "Clean energy industry",
    },
    "AGRICULTURE": {
        "patterns": [
            "CRYSTAL SUGAR", "FARM BUREAU", "DAIRY",
            "FOOD SOLUTIONS", "CARGILL", "ADM",
            "RICE INDUSTRY", "BEER WHOLESALERS",
            "WINE INSTITUTE",
        ],
        "label": "Agriculture industry",
    },
    "GUN_CONTROL": {
        "patterns": [
            "EVERYTOWN", "GIFFORDS", "BRADY", "MOMS DEMAND",
        ],
        "label": "Gun control advocates",
    },
    "GUN_RIGHTS": {
        "patterns": [
            "NATIONAL RIFLE", "GUN OWNERS OF AMERICA",
            "NATIONAL SHOOTING",
        ],
        "label": "Gun rights advocates",
    },
    "REPRODUCTIVE_RIGHTS": {
        "patterns": [
            "PLANNED PARENTHOOD", "EMILY", "NARAL",
            "REPRODUCTIVE FREEDOM",
        ],
        "label": "Reproductive rights groups",
    },
    "AUTO": {
        "patterns": [
            "AUTOMOBILE DEALERS", "NATIONAL AUTO",
        ],
        "label": "Auto industry",
    },
    "FOREIGN_POLICY_ISRAEL": {
        "patterns": [
            "AIPAC", "AMERICAN ISRAEL PUBLIC AFFAIRS",
            "JOINT ACTION COMMITTEE FOR POLITICAL",
        ],
        "label": "Pro-Israel groups",
    },
}

# Vote questions that indicate the "final" most substantive vote on a bill
SUBSTANTIVE_QUESTIONS = [
    "On Passage",
    "On the Conference Report",
    "On the Joint Resolution",
    "On the Concurrent Resolution",
    "On the Resolution",
    "On Cloture",
    "On Overriding the Veto",
]


def load_party_splits(chamber, congresses=None):
    """
    Load party-line vote splits from Voteview data across multiple congresses.
    Returns dict: (congress, roll_number) -> {D_yea, D_nay, R_yea, R_nay}
    """
    if congresses is None:
        congresses = [114, 115, 116, 117, 118, 119]

    prefix = "H" if chamber == "house" else "S"
    splits = {}

    for congress in congresses:
        votes_path = os.path.join(CACHE_DIR, f"{prefix}{congress}_votes.csv")
        members_path = os.path.join(CACHE_DIR, f"{prefix}{congress}_members.csv")

        if not os.path.exists(votes_path) or not os.path.exists(members_path):
            continue

        # Load member party codes
        party_by_icpsr = {}
        with open(members_path) as f:
            for row in csv.DictReader(f):
                try:
                    icpsr = int(float(row["icpsr"]))
                except (ValueError, TypeError):
                    continue
                party_by_icpsr[icpsr] = row.get("party_code", "")

        # Compute splits
        with open(votes_path) as f:
            for row in csv.DictReader(f):
                try:
                    rn = int(float(row["rollnumber"]))
                    icpsr = int(float(row["icpsr"]))
                    cast = int(float(row["cast_code"]))
                except (ValueError, TypeError):
                    continue
                party = party_by_icpsr.get(icpsr, "")

                key = (congress, rn)
                if key not in splits:
                    splits[key] = {"D_yea": 0, "D_nay": 0, "R_yea": 0, "R_nay": 0}

                if party == "100":  # Democrat
                    if cast in (1, 2, 3):
                        splits[key]["D_yea"] += 1
                    elif cast in (4, 5, 6):
                        splits[key]["D_nay"] += 1
                elif party == "200":  # Republican
                    if cast in (1, 2, 3):
                        splits[key]["R_yea"] += 1
                    elif cast in (4, 5, 6):
                        splits[key]["R_nay"] += 1

    return splits


def load_llm_positions():
    """
    Load pre-computed LLM classifications of bill positions per industry category.
    Returns dict: category -> {bill_number: {position, confidence, reason}}
    """
    positions = {}
    if not os.path.exists(LLM_POSITIONS_DIR):
        print(f"  WARNING: LLM positions directory not found: {LLM_POSITIONS_DIR}")
        print("  Run the classification agent first to generate bill position data.")
        return positions

    for filename in os.listdir(LLM_POSITIONS_DIR):
        if filename.startswith("_") or not filename.endswith(".json"):
            continue
        category = filename.replace(".json", "")
        filepath = os.path.join(LLM_POSITIONS_DIR, filename)
        with open(filepath) as f:
            positions[category] = json.load(f)

    return positions


def classify_pac(pac_name):
    """Return the category key for a PAC name, or None."""
    name_upper = pac_name.upper()
    for category, info in PAC_REGISTRY.items():
        for pattern in info["patterns"]:
            if pattern in name_upper:
                return category
    return None


def get_top_pac_donors(member_data, top_n=50):
    """
    Extract the top N PAC donors by amount from a member's funding data.
    Returns list of {name, amount, category, category_label}.
    """
    all_pacs = []

    # Campaign committee PAC donors
    campaign = member_data.get("funding", {}).get("campaign", {})
    for donor in campaign.get("top_pac_donors", []):
        all_pacs.append(donor)

    # Leadership PAC donors
    for lp in member_data.get("funding", {}).get("leadership_pacs", []):
        for donor in lp.get("top_pac_donors", []):
            all_pacs.append(donor)

    # Also check top_industries for backward compat
    for ind in member_data.get("funding", {}).get("top_industries", []):
        if ind.get("code") in ("PAC", "LPAC"):
            for donor in ind.get("donors", []):
                all_pacs.append(donor)

    # Deduplicate by name, summing amounts
    merged = {}
    for p in all_pacs:
        name = p.get("name", "")
        if not name:
            continue
        if name not in merged:
            merged[name] = {"name": name, "amount": 0}
        merged[name]["amount"] += abs(p.get("amount", 0))

    # Sort by amount and take top N
    sorted_pacs = sorted(merged.values(), key=lambda x: -x["amount"])[:top_n]

    # Classify each
    for pac in sorted_pacs:
        category = classify_pac(pac["name"])
        if category:
            pac["category"] = category
            pac["category_label"] = PAC_REGISTRY[category]["label"]
        else:
            pac["category"] = None
            pac["category_label"] = None

    return sorted_pacs


def is_cra_vote(vote):
    """Check if this is a Congressional Review Act disapproval resolution."""
    desc = (vote.get("description", "") or "").lower()
    return any(kw in desc for kw in [
        "congressional disapproval",
        "providing for congressional disapproval",
        "disapproving the rule submitted",
        "disappoving the rule submitted",  # typo in source data
    ])


def is_nomination_or_procedural(vote):
    """
    Check if a vote is a nomination/confirmation, purely procedural,
    or a CRA disapproval resolution. These should NOT be scored.
    """
    # Filter out CRA votes — they're formulaic party-line votes
    if is_cra_vote(vote):
        return True

    desc = (vote.get("description", "") or "").lower()
    question = (vote.get("question", "") or "").lower()

    # Nomination/confirmation votes
    nomination_patterns = [
        r"\bto be\b.*\b(administrator|secretary|director|commissioner|"
        r"ambassador|judge|justice|member of the|chair|under secretary|"
        r"inspector general|attorney general|surgeon general)\b",
        r"\bnominat",
        r"\bconfirmation\b",
    ]
    for pat in nomination_patterns:
        if re.search(pat, desc):
            return True

    # Nomination questions
    if "on the nomination" in question or "on the cloture motion" in question:
        return True

    # Procedural questions (not final passage)
    procedural_questions = [
        "on ordering the previous question",
        "on the motion to table",
        "on motion to suspend the rules",
        "on the motion to discharge",
        "on the point of order",
        "on motion to commit",
        "on motion to recommit",
        "on cloture on the motion to proceed",
        "on the motion to proceed",
        "election of the speaker",
        "providing for consideration",
        "on approving the journal",
        "on the motion to adjourn",
        "quorum call",
    ]
    for pq in procedural_questions:
        if pq in question.lower() or pq in desc:
            return True

    return False


def is_description_too_vague(description):
    """
    Check if a bill description is too vague to reliably classify.
    Short or generic titles like "Breaking the Gridlock Act" don't give
    enough information to confidently determine industry/issue relevance.
    """
    desc = (description or "").strip()
    # Too short to be meaningful
    if len(desc) < 15:
        return True
    # Generic titles that don't describe actual policy content
    vague_patterns = [
        "and for other purposes",
    ]
    # If the title is ONLY a vague phrase (after stripping common wrappers)
    clean = desc.lower().strip()
    if clean in ("", "none", "n/a"):
        return True
    # Very short titles (under ~5 words) are often vague act names
    if len(desc.split()) <= 4 and "appropriation" not in clean:
        return True
    return False


def match_vote_to_categories(vote, categories_with_pacs, llm_positions=None):
    """
    Check if a vote matches any of the active PAC categories using
    pre-computed LLM classifications.
    Returns list of match dicts with category, expected_position, confidence, etc.
    Skips nomination and procedural votes.
    """
    if is_nomination_or_procedural(vote):
        return []

    if not llm_positions:
        return []

    bill_str = (vote.get("bill") or "").strip()
    if not bill_str:
        return []

    # Skip bills with vague descriptions that can't be reliably classified
    if is_description_too_vague(vote.get("description", "")):
        return []

    matches = []
    for category, pacs in categories_with_pacs.items():
        cat_positions = llm_positions.get(category, {})
        bill_info = cat_positions.get(bill_str)
        if not bill_info:
            continue

        position = bill_info.get("position", "")
        confidence = bill_info.get("confidence", 0)

        # Skip unclear or low-confidence classifications
        if position not in ("Yea", "Nay") or confidence < 0.6:
            continue

        donor_names = [p["name"] for p in pacs]
        donor_amounts = sum(p["amount"] for p in pacs)
        matches.append({
            "category": category,
            "expected_position": position,
            "confidence": confidence,
            "reason": bill_info.get("reason", ""),
            "donor_names": donor_names[:3],
            "donor_total": donor_amounts,
            "label": PAC_REGISTRY[category]["label"],
        })

    return matches


def deduplicate_votes(votes):
    """
    Deduplicate votes by bill number.
    Keeps the most substantive vote (On Passage > On Amendment).
    """
    bill_votes = {}
    for v in votes:
        bill = v.get("bill", "")
        if not bill:
            # No bill number — keep as unique
            bill = f"_roll_{v.get('roll_number', 0)}"

        question = v.get("question", "")

        if bill not in bill_votes:
            bill_votes[bill] = v
        else:
            # Replace if this is a more substantive question type
            existing_q = bill_votes[bill].get("question", "")
            for sq in SUBSTANTIVE_QUESTIONS:
                if sq in question and sq not in existing_q:
                    bill_votes[bill] = v
                    break

    return list(bill_votes.values())


def score_member(member_id, member_data, votes_data, llm_positions=None):
    """
    Score donor alignment for a single member.

    Returns alignment data with:
    - overall_pct (weighted by donation amount)
    - total_votes_scored
    - examples with specific donor callouts
    """
    top_pacs = get_top_pac_donors(member_data, top_n=50)

    # Group classified PACs by category
    categories_with_pacs = {}
    for pac in top_pacs:
        cat = pac.get("category")
        if cat:
            if cat not in categories_with_pacs:
                categories_with_pacs[cat] = []
            categories_with_pacs[cat].append(pac)

    if not categories_with_pacs:
        return {
            "overall_pct": 0,
            "total_votes_scored": 0,
            "methodology_url": "/methodology#donor-alignment",
            "examples": [],
        }

    # Get votes and deduplicate by bill
    votes = votes_data.get("recent_votes", [])
    deduped_votes = deduplicate_votes(votes)

    # Score each vote
    scored_votes = []
    for vote in deduped_votes:
        position = vote.get("position")
        if not position or position in ("Absent", "Present", "N/A"):
            continue

        matches = match_vote_to_categories(vote, categories_with_pacs, llm_positions)
        if not matches:
            continue

        # Use the match with the highest donor total (most money at stake)
        best_match = max(matches, key=lambda m: m["donor_total"])

        aligned = position == best_match["expected_position"]

        scored_votes.append({
            "vote_description": vote.get("description", ""),
            "bill": vote.get("bill", ""),
            "date": vote.get("date", ""),
            "member_voted": position,
            "donor_expected": best_match["expected_position"],
            "aligned": aligned,
            "donor_names": best_match["donor_names"],
            "donor_total": best_match["donor_total"],
            "category": best_match["category"],
            "category_label": best_match["label"],
            "confidence": best_match["confidence"],
            "reason": best_match.get("reason", ""),
        })

    if not scored_votes:
        return {
            "overall_pct": 0,
            "total_votes_scored": 0,
            "methodology_url": "/methodology#donor-alignment",
            "examples": [],
        }

    # Calculate weighted alignment score
    total_weight = 0
    weighted_aligned = 0

    for sv in scored_votes:
        weight = sv["donor_total"]
        total_weight += weight
        if sv["aligned"]:
            weighted_aligned += weight

    overall_pct = round(weighted_aligned / total_weight * 100) if total_weight > 0 else 0

    # Select high-confidence examples (confidence >= 0.8) for display
    high_confidence = [sv for sv in scored_votes if sv["confidence"] >= 0.8]

    aligned_examples = [sv for sv in high_confidence if sv["aligned"]]
    against_examples = [sv for sv in high_confidence if not sv["aligned"]]

    # Sort by donor_total (higher stakes = more notable)
    aligned_examples.sort(key=lambda e: -e["donor_total"])
    against_examples.sort(key=lambda e: -e["donor_total"])

    def pick_diverse(examples, n):
        """Pick up to n examples, preferring different categories."""
        picked = []
        seen_categories = set()
        for ex in examples:
            if ex["category"] not in seen_categories and len(picked) < n:
                picked.append(ex)
                seen_categories.add(ex["category"])
        for ex in examples:
            if ex not in picked and len(picked) < n:
                picked.append(ex)
        return picked

    # Pick examples proportional to alignment
    if overall_pct >= 80:
        n_aligned = min(4, len(aligned_examples))
        n_against = min(1, len(against_examples))
    elif overall_pct >= 50:
        n_aligned = min(3, len(aligned_examples))
        n_against = min(2, len(against_examples))
    else:
        n_aligned = min(1, len(aligned_examples))
        n_against = min(4, len(against_examples))

    selected = []
    for ex in pick_diverse(aligned_examples, n_aligned):
        selected.append({
            "vote_description": ex["vote_description"],
            "bill": ex["bill"],
            "date": ex["date"],
            "member_voted": ex["member_voted"],
            "aligned": True,
            "donor_category": ex["category_label"],
            "donor_expected": ex["donor_expected"],
            "confidence": ex["confidence"],
            "reason": ex["reason"],
        })
    for ex in pick_diverse(against_examples, n_against):
        selected.append({
            "vote_description": ex["vote_description"],
            "bill": ex["bill"],
            "date": ex["date"],
            "member_voted": ex["member_voted"],
            "aligned": False,
            "donor_category": ex["category_label"],
            "donor_expected": ex["donor_expected"],
            "confidence": ex["confidence"],
            "reason": ex["reason"],
        })

    return {
        "overall_pct": overall_pct,
        "total_votes_scored": len(scored_votes),
        "methodology_url": "/methodology#donor-alignment",
        "examples": selected,
    }


def main():
    load_dotenv()
    print("Scoring donor alignment...")

    # Load pre-computed LLM classifications
    print("  Loading LLM bill position classifications...")
    llm_positions = load_llm_positions()
    if not llm_positions:
        print("  ERROR: No LLM position data found. Run classification agent first.")
        sys.exit(1)
    total_classified = sum(len(v) for v in llm_positions.values())
    print(f"  Loaded {len(llm_positions)} categories, {total_classified} total bill classifications")

    # Load members
    members_path = os.path.join(RAW_DIR, "members.json")
    if not os.path.exists(members_path):
        print("ERROR: No members.json. Run 01_fetch_members.py first.")
        sys.exit(1)
    with open(members_path) as f:
        members = json.load(f)

    results = {}
    scored_count = 0

    for member in members:
        bio_id = member["bioguide_id"]

        # Load member's full data (with funding info)
        member_path = os.path.join(PUBLIC_MEMBERS_DIR, f"{bio_id}.json")
        if not os.path.exists(member_path):
            continue
        with open(member_path) as f:
            member_data = json.load(f)

        # Load member's votes
        votes_path = os.path.join(PUBLIC_MEMBERS_DIR, f"{bio_id}_votes.json")
        if not os.path.exists(votes_path):
            continue
        with open(votes_path) as f:
            votes_data = json.load(f)

        alignment = score_member(bio_id, member_data, votes_data, llm_positions)
        results[bio_id] = alignment

        if alignment["total_votes_scored"] > 0:
            scored_count += 1

    # Save
    os.makedirs(RAW_DIR, exist_ok=True)
    out_path = os.path.join(RAW_DIR, "donor_alignment.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)

    print(f"Scored {scored_count}/{len(results)} members with donor alignment data")

    # Also patch member JSONs directly
    patched = 0
    for bio_id, alignment in results.items():
        member_path = os.path.join(PUBLIC_MEMBERS_DIR, f"{bio_id}.json")
        if not os.path.exists(member_path):
            continue
        with open(member_path) as f:
            member_data = json.load(f)
        member_data["donor_alignment"] = alignment
        with open(member_path, "w") as f:
            json.dump(member_data, f, indent=2)
        patched += 1

    print(f"Patched {patched} member JSON files")

    # Show test results
    for test_id in ["P000197", "S001150", "P000145"]:
        a = results.get(test_id, {})
        name = "?"
        mp = os.path.join(PUBLIC_MEMBERS_DIR, f"{test_id}.json")
        if os.path.exists(mp):
            with open(mp) as f:
                name = json.load(f).get("name", "?")
        print(f"\n  {name} ({test_id}): {a.get('overall_pct', 0)}% aligned, {a.get('total_votes_scored', 0)} votes")
        for ex in a.get("examples", []):
            tag = "ALIGNED" if ex["aligned"] else "AGAINST"
            print(f"    [{tag}] {ex['vote_description'][:55]} | Donor: {ex.get('donor_name', '')[:30]}")


if __name__ == "__main__":
    main()
