#!/usr/bin/env python3
"""
Score district alignment using MRP-derived opinion estimates from CES data.

Reads district_estimates.csv (generated by run_mrp.R) and compares to
each member's voting record on related issues.

Usage:
    python3 score_district_v2.py --members P000197,S001150,P000145
"""
from __future__ import annotations

import csv
import json
import re
import sys
import argparse
from pathlib import Path

MEMBERS_DIR = Path(__file__).parent.parent / "civic-receipts" / "public" / "data" / "members"
CACHE_DIR = Path(__file__).parent / ".cache"
MRP_DIR = Path(__file__).parent / "mrp"

# === Issue-to-vote mapping ===
# Maps MRP question names to vote keywords and what "support" means in votes.
# support_means_yea: True if supporting the policy = voting Yea on related bills
ISSUE_VOTE_MAP = {
    "guns_bgchecks": {
        "keywords": ["background check", "gun purchase", "firearm purchase"],
        "support_means_yea": True,
        "invert_for": ["disapproval", "disapproving", "repeal"],
    },
    "guns_assaultban": {
        "keywords": ["assault weapon", "assault-style", "semiautomatic",
                      "gun violence", "firearm"],
        "support_means_yea": True,
        "invert_for": ["disapproval", "disapproving", "repeal"],
    },
    "abortion_always": {
        "keywords": ["abortion", "reproductive freedom", "reproductive rights"],
        "support_means_yea": True,
        "invert_for": ["prohibit", "ban", "restrict", "disapproval", "disapproving",
                        "born-alive", "survivors protection"],
    },
    "healthcare_aca": {
        "keywords": ["affordable care act", "\\baca\\b", "health insurance marketplace",
                      "premium tax credit", "health insurance coverage",
                      "health insurance reform"],
        "support_means_yea": True,
        "invert_for": ["repeal", "disapproval", "disapproving", "rescind",
                        "rescission", "reduce funding", "cutting"],
    },
    "enviro_carbon": {
        "keywords": ["climate", "\\bemissions\\b", "carbon", "greenhouse",
                      "\\bepa\\b", "environmental protection agency",
                      "\\bpollution\\b", "clean air"],
        "support_means_yea": True,
        "invert_for": ["disapproval", "disapproving", "repeal", "rescission",
                        "terminate", "strike", "eliminating"],
    },
    "enviro_renewable": {
        "keywords": ["renewable", "clean energy", "solar", "wind energy",
                      "electric vehicle", "energy efficiency"],
        "support_means_yea": True,
        "invert_for": ["disapproval", "disapproving", "repeal", "rescission",
                        "terminate", "eliminating"],
    },
    "immig_legalize": {
        "keywords": ["dreamer", "daca", "dream act", "legal status",
                      "immigration reform", "pathway to citizenship"],
        "support_means_yea": True,
        "invert_for": ["repeal", "disapproval"],
    },
    "immig_wall": {
        "keywords": ["border wall", "border barrier", "border security",
                      "immigration enforcement", "\\bice\\b", "deportation"],
        "support_means_yea": True,
        "invert_for": ["disapproval", "strike"],
    },
}


def load_district_estimates() -> dict[str, dict[str, dict]]:
    """Load MRP estimates. Returns {district: {question: {support_pct, label, topic}}}."""
    estimates_path = MRP_DIR / "district_estimates.csv"
    if not estimates_path.exists():
        print(f"ERROR: {estimates_path} not found. Run run_mrp.R first.")
        sys.exit(1)

    result: dict[str, dict[str, dict]] = {}
    with open(estimates_path) as f:
        for row in csv.DictReader(f):
            cd = row["cd_clean"]
            q = row["question"]
            if cd not in result:
                result[cd] = {}
            result[cd][q] = {
                "support_pct": float(row["support_pct"]),
                "label": row["label"],
                "topic": row["topic"],
                "margin_of_error": int(row["margin_of_error"]),
            }
    return result


def load_rollcalls(chamber: str, congress: int = 119) -> dict:
    """Load rollcall data from cache."""
    prefix = "H" if chamber == "house" else "S"
    cache_path = CACHE_DIR / f"{prefix}{congress}_rollcalls.csv"
    if not cache_path.exists():
        return {}
    rollcalls = {}
    with open(cache_path) as f:
        for row in csv.DictReader(f):
            rn = int(row["rollnumber"])
            rollcalls[rn] = row
    return rollcalls


def score_member(bioguide_id: str, estimates: dict) -> bool:
    """Score district alignment for one member."""
    member_path = MEMBERS_DIR / f"{bioguide_id}.json"
    votes_path = MEMBERS_DIR / f"{bioguide_id}_votes.json"

    if not member_path.exists() or not votes_path.exists():
        print(f"  SKIP: Missing data for {bioguide_id}")
        return False

    with open(member_path) as f:
        member = json.load(f)
    with open(votes_path) as f:
        votes_data = json.load(f)

    chamber = member.get("chamber", "house")
    state = member.get("state", "")
    district = member.get("district", "")

    # Build district key
    if chamber == "senate":
        # For senators, use statewide average across all districts
        state_districts = [cd for cd in estimates if cd.startswith(f"{state}-")]
        if not state_districts:
            print(f"  SKIP: No MRP data for {state}")
            return False
        # Average across all districts in the state
        district_opinion = {}
        for q in ISSUE_VOTE_MAP:
            vals = [estimates[cd][q]["support_pct"] for cd in state_districts
                    if q in estimates.get(cd, {})]
            if vals:
                sample_cd = state_districts[0]
                district_opinion[q] = {
                    "support_pct": round(sum(vals) / len(vals), 1),
                    "label": estimates[sample_cd][q]["label"],
                    "topic": estimates[sample_cd][q]["topic"],
                    "margin_of_error": estimates[sample_cd][q]["margin_of_error"],
                }
        cd_key = f"{state} (statewide avg)"
    else:
        cd_key = f"{state}-{district}"
        if cd_key not in estimates:
            print(f"  SKIP: No MRP data for {cd_key}")
            return False
        district_opinion = {q: estimates[cd_key][q] for q in ISSUE_VOTE_MAP
                           if q in estimates.get(cd_key, {})}

    if not district_opinion:
        print(f"  SKIP: No matching opinion data for {cd_key}")
        return False

    # Build vote lookup
    vote_lookup = {}
    for v in votes_data.get("recent_votes", []):
        vote_lookup[v["roll_number"]] = v

    # Load rollcalls
    congress = votes_data.get("congress", 119)
    rollcalls = load_rollcalls(chamber, congress)

    # Score each issue
    highlights = []
    against_with_donors = []
    issues_scored = 0
    against_count = 0

    # Get donor categories
    donor_cats = set()
    for ex in member.get("donor_alignment", {}).get("examples", []):
        donor_cats.add(ex.get("industry", ""))

    for q_name, vote_config in ISSUE_VOTE_MAP.items():
        if q_name not in district_opinion:
            continue

        opinion = district_opinion[q_name]
        support_pct = opinion["support_pct"]
        keywords = vote_config["keywords"]
        invert_patterns = vote_config["invert_for"]

        # Find matching votes
        aligned_votes = 0
        total_votes = 0

        for rn, rc in rollcalls.items():
            desc = (rc.get("vote_desc", "") + " " + rc.get("bill_number", "")).lower()
            question = rc.get("vote_question", "").lower()

            # Skip procedural and nominations
            if desc.startswith("providing for consideration"):
                continue
            if "nomination" in question:
                continue
            if "motion to recommit" in question:
                continue
            if any(p in desc for p in ["to be secretary", "to be deputy",
                                        "to be an assistant", "to be administrator"]):
                continue

            # Check if vote matches this issue
            matched = False
            for kw in keywords:
                if "\\" in kw:
                    # Regex pattern (contains word boundaries)
                    if re.search(kw, desc):
                        matched = True
                        break
                else:
                    if kw in desc:
                        matched = True
                        break
            if not matched:
                continue

            vote = vote_lookup.get(rn)
            if not vote or vote["position"] not in ("Yea", "Nay"):
                continue

            total_votes += 1

            # Determine if the vote context inverts the meaning
            inverted = any(p in desc for p in invert_patterns)

            # What does the district want?
            # If >50% support, district wants Yea (or Nay if inverted)
            district_wants_yea = support_pct > 50
            if inverted:
                district_wants_yea = not district_wants_yea

            expected_position = "Yea" if district_wants_yea else "Nay"
            if vote["position"] == expected_position:
                aligned_votes += 1

        if total_votes == 0:
            continue

        issues_scored += 1
        is_aligned = aligned_votes > total_votes / 2

        if not is_aligned:
            against_count += 1

        # Determine the rep's predominant position on this issue
        if aligned_votes > total_votes / 2:
            # Mostly voted as expected — their position matches expected_position
            rep_vote = expected_position
        else:
            # Mostly voted opposite to expected
            rep_vote = "Nay" if expected_position == "Yea" else "Yea"

        alignment_word = "with" if is_aligned else "against"
        member_position = f"Voted {rep_vote}, {alignment_word} district"

        highlight = {
            "issue": opinion["label"],
            "district_support_pct": support_pct,
            "margin_of_error": opinion["margin_of_error"],
            "member_position": member_position,
            "aligned_with_electorate": is_aligned,
            "aligned_with_donors": False,
        }
        highlights.append(highlight)

    against_pct = round(against_count / issues_scored * 100) if issues_scored > 0 else 0

    member["electorate_alignment"] = {
        "issues_scored": issues_scored,
        "against_electorate_pct": against_pct,
        "highlights": highlights,
        "against_electorate_with_donors": against_with_donors,
        "methodology": "MRP on CES 2018-2021 survey data (164,700 respondents)",
    }

    with open(member_path, "w") as f:
        json.dump(member, f, indent=2)

    aligned_pct = 100 - against_pct
    print(f"  OK: {member['name']} ({cd_key}) — {aligned_pct}% aligned ({issues_scored} issues)")
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--members", help="Comma-separated bioguide IDs")
    parser.add_argument("--all", action="store_true")
    args = parser.parse_args()

    if args.all:
        member_ids = [f.stem for f in MEMBERS_DIR.glob("*.json") if "_" not in f.stem]
    elif args.members:
        member_ids = args.members.split(",")
    else:
        print("Specify --members or --all")
        sys.exit(1)

    estimates = load_district_estimates()
    print(f"Loaded MRP estimates for {len(estimates)} districts\n")

    success = 0
    for bid in member_ids:
        if score_member(bid.strip(), estimates):
            success += 1

    print(f"\nDone. Scored {success}/{len(member_ids)} members.")


if __name__ == "__main__":
    main()
